main: aliuly\itemcasepe\Main
api: 2.0.0
load: POSTWORLD
depend: [ libcommon ]

name: ItemCasePE
description: An implementation of Bukkit's ItemCase
version: 1.1.0
author: aliuly
website: http://github.com/Muirfield/ItemCasePE

commands:
  itemcase:
    description: ItemCase management command
    usage: "/itemcase [add|cancel|respawn]"
    aliases: [ic]
    permission: itemcase.cmd

permissions:
 itemcase:
  default: false
  description: "allow players access to all itemcase features"
  children:
   itemcase.cmd:
    default: op
    description: "allow players access to the itemcase command"
   itemcase.destroy:
    default: op
    description: "allow players to destroy cases"
